#define AXIS_STATE_COMPLETE 0
#define AXIS_STATE_RUNNING 1
#define AXIS_STATE_ERROR_LIMIT_SWITCH 2

#define DISPENSER_STATE_BLOCKED 6
#define DISPENSER_STATE_IDLING 0
#define DISPENSER_STATE_SENT 1
#define DISPENSER_STATE_ACKNOWLEDGED 2
#define DISPENSER_STATE_ERROR_IR_SENSOR_FAILURE 4
#define DISPENSER_STATE_ERROR_MARKER_NOT_DETECTED 5